site_name: Tech Notes
site_url: https://healthfin.solutions/notes/
use_directory_urls: true
theme:
  name: material
  palette:
  - scheme: default
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/weather-night
      name: Switch to light mode
extra_javascript:
- https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
- files/inject_edit_page.js
extra_css:
- files/extra.css
markdown_extensions:
- pymdownx.highlight:
    linenums: true
    use_pygments: true
- pymdownx.superfences
plugins:
- search
- print-site
nav:
- Home: index.md
- Python:
  - Intro:
      - What is Python: Python/docs_1_what_is_python.md
      - How to Use: Python/docs_2_how_to_use.md
      - Writing Code: Python/docs_3_writing_code.md
  - Advanced Coding:
      - Advanced Coding Topics: Python/docs_5_advanced_topics.md
      - Important Libraries: Python/docs_7_important_libraries.md
      - Standard Library Gems: Python/docs_9_std_lib.md
      - Testing Code: Python/testing.md
  - Execution and Deployment:
      - Building Large Projects: Python/docs_4_building_large_projects.md
      - Deploying Python Programs: Python/deployment.md
      - Publishing Projects: Python/docs_6_publishing_project.md
  - Other Tools:
      - Python uv: Python/python_uv.md
      - Documentation Libraries: Python/docs_8_documentation.md
- Git & GitHub:
    - Git Basics: Git/basics.md
    - Remotes: Git/remotes.md
    - Branches: Git/branches.md
- Docker:
    - Intro: Docker/intro.md
    - Basics: Docker/basics.md
    - Docker Compose: Docker/docker_compose.md
    - Creating Images (Dockerfile): Docker/docker_images.md
- Self Hosting:
  - General:
      - Linux: self_host/docs_104_linux.md
      - SSH: self_host/docs_103_ssh.md
      - Backups: self_host/docs_199_backups.md
      - Login Security: self_host/login_attempts.md
      - Storage vs Compute: self_host/storage_vs_compute.md
      - NAS: self_host/nas.md
  - Programs:
      - Ollama (Host an LLM): AI/docs_105_local_llm.md
      - Samba (Shared Drive): self_host/samba.md
      - Syncthing (File Sync): self_host/syncthing.md
      - Plex/Jellyfin (Video Streaming): self_host/video_streaming.md
    #  - Portainer (Docker UI):
      - Frigate (CCTV): self_host/frigate.md
    #  - Databases:
    #  - Immich (Photos):
    #  - netdata (resource management):
      - Caddy (reverse proxy & web server): self_host/web_server.md
      - WireGuard (VPN): self_host/wireguard.md
      - GitHub Remotes: Git/remotes.md
      - Forgejo: self_host/foregejo.md
#  - Adguard (DNS):
- Networking:
    - General Networking: Networking/docs_100_networking.md
    - Servers: Networking/docs_100_servers.md
    - Caddy: Networking/docs_101_caddy.md
    - DNS: Networking/docs_102_dns_server.md
- Windows:
    - Password Policy: windows_admin/password_policy.md
- Databases:
    - DuckDB: databases/duckdb.md
- Video Processing:
    - FFmpeg: Video Processing/docs_200_ffmpeg.md
    - Streaming: Video Processing/docs_200_streaming.md
- AI:
    - Ollama: AI/docs_105_local_llm.md
    - MCP: AI/mcp.md
    - Claude Code: AI/claude_code.md
- Low-Level:
    - Learning Paths: Low Level/foundations.md
    - Drivers: Low Level/drivers.md
- Rust: Rust/rust01.md
